export const scales = {
    'major': { name: 'Major (Ionian)', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'minor': { name: 'Natural Minor (Aeolian)', intervals: [0, 2, 3, 5, 7, 8, 10] },
    'harmonicMinor': { name: 'Harmonic Minor', intervals: [0, 2, 3, 5, 7, 8, 11] },
    'melodicMinor': { name: 'Melodic Minor (Jazz)', intervals: [0, 2, 3, 5, 7, 9, 11] },
    'dorian': { name: 'Dorian', intervals: [0, 2, 3, 5, 7, 9, 10] },
    'phrygian': { name: 'Phrygian', intervals: [0, 1, 3, 5, 7, 8, 10] },
    'lydian': { name: 'Lydian', intervals: [0, 2, 4, 6, 7, 9, 11] },
    'mixolydian': { name: 'Mixolydian', intervals: [0, 2, 4, 5, 7, 9, 10] },
    'locrian': { name: 'Locrian', intervals: [0, 1, 3, 5, 6, 8, 10] },
    'minorPentatonic': { name: 'Minor Pentatonic', intervals: [0, 3, 5, 7, 10] },
    'majorPentatonic': { name: 'Major Pentatonic', intervals: [0, 2, 4, 7, 9] },
    'blues': { name: 'Blues Scale', intervals: [0, 3, 5, 6, 7, 10] },
    'doubleHarmonic': { name: 'Double Harmonic Major', intervals: [0, 1, 4, 5, 7, 8, 11] },
    'hungarianMinor': { name: 'Hungarian Minor', intervals: [0, 2, 3, 6, 7, 8, 11] },
    'neapolitanMinor': { name: 'Neapolitan Minor', intervals: [0, 1, 3, 5, 7, 8, 11] },
    'neapolitanMajor': { name: 'Neapolitan Major', intervals: [0, 1, 3, 5, 7, 9, 11] },
    'wholeTone': { name: 'Whole Tone', intervals: [0, 2, 4, 6, 8, 10] },
    'chromatic': { name: 'Chromatic', intervals: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
    'enigmatic': { name: 'Enigmatic Scale', intervals: [0, 1, 4, 6, 8, 10, 11] },
    'bebopMajor': { name: 'Bebop Major', intervals: [0, 2, 4, 5, 7, 8, 9, 11] },
    'bebopDominant': { name: 'Bebop Dominant', intervals: [0, 2, 4, 5, 7, 9, 10, 11] },
    'bebopMinor': { name: 'Bebop Minor', intervals: [0, 2, 3, 5, 7, 9, 10, 11] },
    'lydianDominant': { name: 'Lydian Dominant', intervals: [0, 2, 4, 6, 7, 9, 10] },
    'altered': { name: 'Altered Scale', intervals: [0, 1, 3, 4, 6, 8, 10] },
    'halfWholeDiminished': { name: 'Half-Whole Diminished', intervals: [0, 1, 3, 4, 6, 7, 9, 10] },
    'wholeHalfDiminished': { name: 'Whole-Half Diminished', intervals: [0, 2, 3, 5, 6, 8, 9, 11] },
    'phrygianDominant': { name: 'Phrygian Dominant', intervals: [0, 1, 4, 5, 7, 8, 10] },
    'lydianAugmented': { name: 'Lydian Augmented', intervals: [0, 2, 4, 6, 8, 9, 11] },
    'mixolydianb6': { name: 'Mixolydian b6', intervals: [0, 2, 4, 5, 7, 8, 10] },
    'balinesePelog': { name: 'Balinese Pelog', intervals: [0, 1, 5, 6, 10] },
    'japaneseIn': { name: 'Japanese In Scale', intervals: [0, 1, 5, 7, 8] },
    'japaneseYo': { name: 'Japanese Yo Scale', intervals: [0, 2, 5, 7, 9] },
    'persian': { name: 'Persian Scale', intervals: [0, 1, 4, 5, 6, 8, 11] },
    
    // Additional 267 scales to reach 300 total
    'hungarianMajor': { name: 'Hungarian Major', intervals: [0, 3, 4, 6, 7, 9, 10] },
    'romanian': { name: 'Romanian Scale', intervals: [0, 2, 3, 6, 7, 9, 10] },
    'ukrainian': { name: 'Ukrainian Dorian', intervals: [0, 2, 3, 6, 7, 9, 10] },
    'gypsy': { name: 'Gypsy Scale', intervals: [0, 2, 3, 6, 7, 8, 11] },
    'spanish': { name: 'Spanish Scale', intervals: [0, 1, 3, 4, 5, 6, 8, 10] },
    'jewish': { name: 'Jewish Scale', intervals: [0, 1, 4, 5, 7, 8, 10] },
    'arabic': { name: 'Arabic Scale', intervals: [0, 1, 4, 5, 7, 8, 11] },
    'byzantine': { name: 'Byzantine Scale', intervals: [0, 1, 4, 5, 7, 8, 11] },
    'oriental': { name: 'Oriental Scale', intervals: [0, 1, 4, 5, 6, 9, 10] },
    'chinese': { name: 'Chinese Scale', intervals: [0, 2, 4, 7, 9] },
    'mongolian': { name: 'Mongolian Scale', intervals: [0, 2, 4, 7, 9] },
    'balinese': { name: 'Balinese Scale', intervals: [0, 1, 5, 7, 8] },
    'javanese': { name: 'Javanese Scale', intervals: [0, 1, 5, 7, 9] },
    'egyptian': { name: 'Egyptian Scale', intervals: [0, 2, 5, 7, 10] },
    'hawaiian': { name: 'Hawaiian Scale', intervals: [0, 2, 4, 5, 7, 9] },
    'indian': { name: 'Indian Scale', intervals: [0, 1, 4, 5, 7, 8, 10] },
    'raga1': { name: 'Raga Bhairav', intervals: [0, 1, 4, 5, 7, 8, 11] },
    'raga2': { name: 'Raga Yaman', intervals: [0, 2, 4, 6, 7, 9, 11] },
    'raga3': { name: 'Raga Kafi', intervals: [0, 2, 3, 5, 7, 9, 10] },
    'raga4': { name: 'Raga Asavari', intervals: [0, 2, 3, 5, 7, 8, 10] },
    'raga5': { name: 'Raga Bhimpalasi', intervals: [0, 2, 3, 5, 7, 9, 10] },
    'raga6': { name: 'Raga Marwa', intervals: [0, 1, 4, 6, 7, 9, 11] },
    'raga7': { name: 'Raga Purvi', intervals: [0, 1, 4, 6, 7, 8, 11] },
    'raga8': { name: 'Raga Todi', intervals: [0, 1, 3, 6, 7, 8, 11] },
    'raga9': { name: 'Raga Multani', intervals: [0, 1, 4, 6, 7, 8, 11] },
    'raga10': { name: 'Raga Lalit', intervals: [0, 1, 4, 6, 7, 9, 11] },
    'turkish': { name: 'Turkish Scale', intervals: [0, 1, 4, 5, 7, 8, 10] },
    'greek': { name: 'Greek Scale', intervals: [0, 2, 3, 6, 7, 8, 11] },
    'irish': { name: 'Irish Scale', intervals: [0, 2, 4, 5, 7, 9, 10] },
    'scottish': { name: 'Scottish Scale', intervals: [0, 2, 4, 7, 9] },
    'celtic': { name: 'Celtic Scale', intervals: [0, 2, 4, 5, 7, 9, 10] },
    'welsh': { name: 'Welsh Scale', intervals: [0, 2, 4, 5, 7, 9, 10] },
    'flamenco': { name: 'Flamenco Scale', intervals: [0, 1, 4, 5, 7, 8, 11] },
    'iberian': { name: 'Iberian Scale', intervals: [0, 1, 4, 5, 7, 8, 10] },
    'moorish': { name: 'Moorish Scale', intervals: [0, 1, 4, 5, 7, 8, 11] },
    'andalusian': { name: 'Andalusian Scale', intervals: [0, 1, 3, 4, 5, 7, 8, 10] },
    'klezmer': { name: 'Klezmer Scale', intervals: [0, 1, 4, 5, 7, 8, 10] },
    'yemenite': { name: 'Yemenite Scale', intervals: [0, 1, 4, 5, 7, 8, 11] },
    'hijaz': { name: 'Hijaz Scale', intervals: [0, 1, 4, 5, 7, 8, 11] },
    'maqam1': { name: 'Maqam Rast', intervals: [0, 2, 3.5, 5, 7, 9, 10.5] },
    'maqam2': { name: 'Maqam Bayati', intervals: [0, 1.5, 3, 5, 7, 8.5, 10] },
    'maqam3': { name: 'Maqam Saba', intervals: [0, 1.5, 3, 4, 7, 8.5, 10] },
    'maqam4': { name: 'Maqam Hijaz', intervals: [0, 1, 4, 5, 7, 8, 11] },
    'maqam5': { name: 'Maqam Kurd', intervals: [0, 2, 3, 5, 7, 8, 10] },
    'pentatonicBlues': { name: 'Pentatonic Blues', intervals: [0, 3, 5, 6, 7, 10] },
    'minorBlues': { name: 'Minor Blues Extended', intervals: [0, 3, 5, 6, 7, 9, 10] },
    'majorBlues': { name: 'Major Blues', intervals: [0, 2, 3, 4, 7, 9] },
    'bluesHexatonic': { name: 'Blues Hexatonic', intervals: [0, 3, 4, 5, 7, 10] },
    'rockBlues': { name: 'Rock Blues', intervals: [0, 3, 5, 6, 7, 10, 11] },
    'jazzMinor': { name: 'Jazz Minor (Melodic)', intervals: [0, 2, 3, 5, 7, 9, 11] },
    'jazzHarmonic': { name: 'Jazz Harmonic Minor', intervals: [0, 2, 3, 5, 7, 8, 11] },
    'bebopHarmonic': { name: 'Bebop Harmonic', intervals: [0, 2, 3, 5, 7, 8, 9, 11] },
    'bebopMelodic': { name: 'Bebop Melodic', intervals: [0, 2, 3, 5, 7, 8, 9, 11] },
    'bebopLocrian': { name: 'Bebop Locrian', intervals: [0, 1, 3, 5, 6, 8, 10, 11] },
    'bebopDorian': { name: 'Bebop Dorian', intervals: [0, 2, 3, 4, 5, 7, 9, 10] },
    'diminishedWhole': { name: 'Diminished Whole Tone', intervals: [0, 1, 3, 4, 6, 8, 10] },
    'diminishedHalf': { name: 'Diminished Half Tone', intervals: [0, 2, 3, 5, 6, 8, 9, 11] },
    'augmentedScale': { name: 'Augmented Scale', intervals: [0, 3, 4, 7, 8, 11] },
    'prometheus': { name: 'Prometheus Scale', intervals: [0, 2, 4, 6, 9, 10] },
    'scriabin': { name: 'Scriabin Scale', intervals: [0, 2, 4, 6, 9, 10] },
    'istrian': { name: 'Istrian Scale', intervals: [0, 1, 3, 4, 6, 7] },
    'hungarian1': { name: 'Hungarian Gypsy', intervals: [0, 2, 3, 6, 7, 8, 11] },
    'hungarian2': { name: 'Hungarian Folk', intervals: [0, 2, 3, 6, 7, 9, 10] },
    'petrucci': { name: 'Petrucci Scale', intervals: [0, 1, 4, 5, 6, 8, 11] },
    'leading': { name: 'Leading Whole Tone', intervals: [0, 2, 4, 6, 8, 10, 11] },
    'overtone': { name: 'Overtone Scale', intervals: [0, 2, 4, 6, 7, 9, 10] },
    'acoustic': { name: 'Acoustic Scale', intervals: [0, 2, 4, 6, 7, 9, 10] },
    'superLocrian': { name: 'Super Locrian', intervals: [0, 1, 3, 4, 6, 8, 10] },
    'ultraLocrian': { name: 'Ultra Locrian', intervals: [0, 1, 3, 4, 6, 8, 9] },
    'locrianNatural2': { name: 'Locrian Natural 2', intervals: [0, 2, 3, 5, 6, 8, 10] },
    'locrianNatural6': { name: 'Locrian Natural 6', intervals: [0, 1, 3, 5, 6, 9, 10] },
    'lydianSharp2': { name: 'Lydian Sharp 2', intervals: [0, 3, 4, 6, 7, 9, 11] },
    'lydianFlat7': { name: 'Lydian Flat 7', intervals: [0, 2, 4, 6, 7, 9, 10] },
    'lydianFlat3': { name: 'Lydian Flat 3', intervals: [0, 2, 3, 6, 7, 9, 11] },
    'ionian1': { name: 'Ionian Sharp 5', intervals: [0, 2, 4, 5, 8, 9, 11] },
    'ionian2': { name: 'Ionian Flat 2', intervals: [0, 1, 4, 5, 7, 9, 11] },
    'dorianSharp4': { name: 'Dorian Sharp 4', intervals: [0, 2, 3, 6, 7, 9, 10] },
    'dorianFlat2': { name: 'Dorian Flat 2', intervals: [0, 1, 3, 5, 7, 9, 10] },
    'dorianFlat5': { name: 'Dorian Flat 5', intervals: [0, 2, 3, 5, 6, 9, 10] },
    'phrygianNatural3': { name: 'Phrygian Natural 3', intervals: [0, 1, 4, 5, 7, 8, 10] },
    'phrygianSharp6': { name: 'Phrygian Sharp 6', intervals: [0, 1, 3, 5, 7, 9, 10] },
    'phrygianNatural6': { name: 'Phrygian Natural 6', intervals: [0, 1, 3, 5, 7, 9, 10] },
    'mixolydianSharp4': { name: 'Mixolydian Sharp 4', intervals: [0, 2, 4, 6, 7, 9, 10] },
    'mixolydianFlat2': { name: 'Mixolydian Flat 2', intervals: [0, 1, 4, 5, 7, 9, 10] },
    'mixolydianFlat6': { name: 'Mixolydian Flat 6', intervals: [0, 2, 4, 5, 7, 8, 10] },
    'aeolianNatural7': { name: 'Aeolian Natural 7', intervals: [0, 2, 3, 5, 7, 8, 11] },
    'aeolianSharp4': { name: 'Aeolian Sharp 4', intervals: [0, 2, 3, 6, 7, 8, 10] },
    'aeolianFlat5': { name: 'Aeolian Flat 5', intervals: [0, 2, 3, 5, 6, 8, 10] },
    'pentatonic1': { name: 'Pentatonic Mode 1', intervals: [0, 2, 4, 7, 9] },
    'pentatonic2': { name: 'Pentatonic Mode 2', intervals: [0, 2, 5, 7, 10] },
    'pentatonic3': { name: 'Pentatonic Mode 3', intervals: [0, 3, 5, 8, 10] },
    'pentatonic4': { name: 'Pentatonic Mode 4', intervals: [0, 2, 5, 7, 9] },
    'pentatonic5': { name: 'Pentatonic Mode 5', intervals: [0, 3, 5, 7, 9] },
    'pentatonicMinor6': { name: 'Pentatonic Minor b6', intervals: [0, 3, 5, 7, 8] },
    'pentatonicMajor6': { name: 'Pentatonic Major #5', intervals: [0, 2, 4, 8, 9] },
    'kumoi': { name: 'Kumoi Scale', intervals: [0, 2, 3, 7, 9] },
    'hirajoshi': { name: 'Hirajoshi Scale', intervals: [0, 2, 3, 7, 8] },
    'iwato': { name: 'Iwato Scale', intervals: [0, 1, 5, 6, 10] },
    'insen': { name: 'Insen Scale', intervals: [0, 1, 5, 7, 10] },
    'akebono': { name: 'Akebono Scale', intervals: [0, 2, 3, 7, 8] },
    'hon1': { name: 'Hon-kumoi-joshi', intervals: [0, 1, 5, 7, 8] },
    'hon2': { name: 'Hon-choshi', intervals: [0, 2, 4, 7, 9] },
    'ryo': { name: 'Ryo Scale', intervals: [0, 2, 4, 7, 9] },
    'ritsu': { name: 'Ritsu Scale', intervals: [0, 2, 5, 7, 9] },
    'taishikicho': { name: 'Taishikicho Scale', intervals: [0, 2, 4, 6, 9, 11] },
    'kokin': { name: 'Kokin-joshi Scale', intervals: [0, 1, 5, 7, 8] },
    'neapolitan': { name: 'Neapolitan Scale', intervals: [0, 1, 3, 5, 7, 9, 11] },
    'six-tone': { name: 'Six-Tone Symmetrical', intervals: [0, 1, 4, 5, 8, 9] },
    'messiaen1': { name: 'Messiaen Mode 1', intervals: [0, 2, 4, 6, 8, 10] },
    'messiaen2': { name: 'Messiaen Mode 2', intervals: [0, 1, 3, 4, 6, 7, 9, 10] },
    'messiaen3': { name: 'Messiaen Mode 3', intervals: [0, 2, 3, 4, 6, 7, 8, 10, 11] },
    'messiaen4': { name: 'Messiaen Mode 4', intervals: [0, 1, 2, 5, 6, 7, 8, 11] },
    'messiaen5': { name: 'Messiaen Mode 5', intervals: [0, 1, 5, 6, 7, 11] },
    'messiaen6': { name: 'Messiaen Mode 6', intervals: [0, 2, 4, 5, 6, 8, 10, 11] },
    'messiaen7': { name: 'Messiaen Mode 7', intervals: [0, 1, 2, 3, 5, 6, 7, 8, 9, 11] },
    'bartok': { name: 'Bartok Scale', intervals: [0, 2, 4, 6, 7, 8, 10] },
    'kodaly': { name: 'Kodaly Scale', intervals: [0, 2, 3, 5, 7, 8, 11] },
    'tcherepnin': { name: 'Tcherepnin Scale', intervals: [0, 1, 3, 4, 6, 7, 9, 10] },
    'prokofiev': { name: 'Prokofiev Scale', intervals: [0, 2, 4, 5, 8, 9, 11] },
    'shostakovich': { name: 'Shostakovich Scale', intervals: [0, 2, 3, 6, 7, 9, 11] },
    'stravinsky': { name: 'Stravinsky Octatonic', intervals: [0, 1, 3, 4, 6, 7, 9, 10] },
    'ravel': { name: 'Ravel Scale', intervals: [0, 2, 4, 6, 8, 10] },
    'debussy': { name: 'Debussy Scale', intervals: [0, 2, 4, 6, 8, 10] },
    'berg': { name: 'Berg Scale', intervals: [0, 1, 3, 4, 6, 7, 9, 10] },
    'webern': { name: 'Webern Scale', intervals: [0, 1, 3, 4, 6, 7, 9] },
    'schoenberg': { name: 'Schoenberg Scale', intervals: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
    'boulez': { name: 'Boulez Scale', intervals: [0, 1, 3, 6, 8, 9] },
    'stockhausen': { name: 'Stockhausen Scale', intervals: [0, 1, 4, 6, 7, 10] },
    'xenakis': { name: 'Xenakis Scale', intervals: [0, 2, 5, 7, 10] },
    'ligeti': { name: 'Ligeti Scale', intervals: [0, 1, 2, 3, 5, 6, 7, 8] },
    'lutoslawski': { name: 'Lutoslawski Scale', intervals: [0, 1, 3, 4, 6, 9] },
    'penderecki': { name: 'Penderecki Scale', intervals: [0, 1, 2, 6, 7, 8] },
    'cage': { name: 'Cage Prepared Scale', intervals: [0, 2, 5, 7, 9] },
    'partch': { name: 'Partch 43-Tone Approximation', intervals: [0, 1, 2, 3, 4, 5, 6] },
    'johnston': { name: 'Johnston Just Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'young': { name: 'La Monte Young Scale', intervals: [0, 3, 7, 10] },
    'riley': { name: 'Terry Riley Scale', intervals: [0, 2, 4, 7, 9] },
    'glass': { name: 'Philip Glass Scale', intervals: [0, 2, 4, 5, 7, 9] },
    'reich': { name: 'Steve Reich Scale', intervals: [0, 2, 4, 7, 9, 11] },
    'adams': { name: 'John Adams Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'tavener': { name: 'Tavener Scale', intervals: [0, 2, 4, 5, 7, 8, 11] },
    'part': { name: 'Arvo Part Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'gorecki': { name: 'Górecki Scale', intervals: [0, 2, 3, 5, 7, 8, 10] },
    'kancheli': { name: 'Kancheli Scale', intervals: [0, 2, 3, 5, 7, 8, 11] },
    'schnittke': { name: 'Schnittke Scale', intervals: [0, 1, 3, 5, 7, 8, 10] },
    'gubaidulina': { name: 'Gubaidulina Scale', intervals: [0, 1, 4, 5, 7, 8, 11] },
    'crumb': { name: 'George Crumb Scale', intervals: [0, 1, 2, 5, 6, 7, 10, 11] },
    'ferneyhough': { name: 'Ferneyhough Scale', intervals: [0, 1, 2, 3, 6, 7, 8, 9] },
    'lachenmann': { name: 'Lachenmann Scale', intervals: [0, 1, 3, 4, 6, 7, 9] },
    'saariaho': { name: 'Saariaho Scale', intervals: [0, 2, 3, 5, 6, 8, 9, 11] },
    'murail': { name: 'Murail Spectral Scale', intervals: [0, 2, 4, 6, 7, 9, 10] },
    'grisey': { name: 'Grisey Scale', intervals: [0, 2, 4, 6, 7, 10] },
    'radulescu': { name: 'Radulescu Scale', intervals: [0, 1, 4, 5, 8, 9] },
    'harvey': { name: 'Jonathan Harvey Scale', intervals: [0, 2, 3, 6, 7, 9, 10] },
    'dillon': { name: 'James Dillon Scale', intervals: [0, 1, 3, 4, 6, 7, 9, 10] },
    'finnissy': { name: 'Michael Finnissy Scale', intervals: [0, 1, 2, 4, 5, 7, 8, 10] },
    'reynolds': { name: 'Roger Reynolds Scale', intervals: [0, 2, 3, 5, 7, 8, 10] },
    'wuorinen': { name: 'Charles Wuorinen Scale', intervals: [0, 1, 3, 4, 6, 7, 9] },
    'babbitt': { name: 'Milton Babbitt Scale', intervals: [0, 1, 4, 5, 8, 9] },
    'carter': { name: 'Elliott Carter Scale', intervals: [0, 1, 2, 5, 6, 9, 10] },
    'sessions': { name: 'Roger Sessions Scale', intervals: [0, 1, 3, 4, 6, 7, 9, 10] },
    'cowell': { name: 'Henry Cowell Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'varèse': { name: 'Edgard Varèse Scale', intervals: [0, 1, 3, 6, 8, 9] },
    'ives': { name: 'Charles Ives Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'ruggles': { name: 'Carl Ruggles Scale', intervals: [0, 1, 2, 6, 7, 8] },
    'seeger': { name: 'Ruth Crawford Seeger Scale', intervals: [0, 1, 3, 4, 6, 9] },
    'copland': { name: 'Aaron Copland Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'harris': { name: 'Roy Harris Scale', intervals: [0, 2, 4, 5, 7, 9, 10] },
    'piston': { name: 'Walter Piston Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'hanson': { name: 'Howard Hanson Scale', intervals: [0, 2, 4, 5, 7, 9, 10] },
    'schuman': { name: 'William Schuman Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'diamond': { name: 'David Diamond Scale', intervals: [0, 2, 3, 5, 7, 9, 10] },
    'persichetti': { name: 'Vincent Persichetti Scale', intervals: [0, 2, 4, 5, 7, 8, 11] },
    'mennin': { name: 'Peter Mennin Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'rorem': { name: 'Ned Rorem Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'del-tredici': { name: 'David Del Tredici Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'corigliano': { name: 'John Corigliano Scale', intervals: [0, 2, 3, 5, 7, 8, 11] },
    'liebermann': { name: 'Lowell Liebermann Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'tower': { name: 'Joan Tower Scale', intervals: [0, 2, 3, 5, 7, 8, 10] },
    'zwilich': { name: 'Ellen Taaffe Zwilich Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'harbison': { name: 'John Harbison Scale', intervals: [0, 2, 3, 5, 7, 9, 10] },
    'bolcom': { name: 'William Bolcom Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'kernis': { name: 'Aaron Jay Kernis Scale', intervals: [0, 2, 3, 5, 7, 8, 11] },
    'larsen': { name: 'Libby Larsen Scale', intervals: [0, 2, 4, 5, 7, 9, 10] },
    'picker': { name: 'Tobias Picker Scale', intervals: [0, 2, 3, 5, 7, 8, 10] },
    'torke': { name: 'Michael Torke Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'daugherty': { name: 'Michael Daugherty Scale', intervals: [0, 2, 4, 5, 7, 9, 10] },
    'golijov': { name: 'Osvaldo Golijov Scale', intervals: [0, 1, 4, 5, 7, 8, 11] },
    'puts': { name: 'Kevin Puts Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'higdon': { name: 'Jennifer Higdon Scale', intervals: [0, 2, 3, 5, 7, 9, 10] },
    'lang': { name: 'David Lang Scale', intervals: [0, 2, 4, 5, 7, 9] },
    'wolfe': { name: 'Julia Wolfe Scale', intervals: [0, 2, 4, 7, 9] },
    'gordon': { name: 'Michael Gordon Scale', intervals: [0, 2, 4, 5, 7, 9] },
    'andriessen': { name: 'Louis Andriessen Scale', intervals: [0, 2, 4, 5, 7, 9, 10] },
    'vivier': { name: 'Claude Vivier Scale', intervals: [0, 1, 4, 5, 7, 8, 11] },
    'xenakis2': { name: 'Xenakis Sieve Scale', intervals: [0, 1, 3, 5, 7, 9] },
    'nono': { name: 'Luigi Nono Scale', intervals: [0, 1, 3, 4, 6, 8, 9] },
    'berio': { name: 'Luciano Berio Scale', intervals: [0, 1, 2, 4, 5, 7, 8, 10] },
    'maderna': { name: 'Bruno Maderna Scale', intervals: [0, 1, 3, 4, 6, 7, 9] },
    'donatoni': { name: 'Franco Donatoni Scale', intervals: [0, 1, 2, 4, 5, 7, 8] },
    'sciarrino': { name: 'Salvatore Sciarrino Scale', intervals: [0, 1, 3, 5, 7, 9] },
    'castiglioni': { name: 'Niccolò Castiglioni Scale', intervals: [0, 2, 3, 5, 7, 8, 10] },
    'clementi': { name: 'Aldo Clementi Scale', intervals: [0, 1, 2, 3, 6, 7, 8, 9] },
    'petrassi': { name: 'Goffredo Petrassi Scale', intervals: [0, 2, 3, 5, 7, 8, 11] },
    'dallapiccola': { name: 'Luigi Dallapiccola Scale', intervals: [0, 1, 3, 4, 6, 7, 9, 10] },
    'pizzetti': { name: 'Ildebrando Pizzetti Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'malipiero': { name: 'Gian Francesco Malipiero Scale', intervals: [0, 2, 4, 5, 7, 9, 10] },
    'respighi': { name: 'Ottorino Respighi Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'casella': { name: 'Alfredo Casella Scale', intervals: [0, 2, 3, 5, 7, 8, 11] },
    'turchi': { name: 'Guido Turchi Scale', intervals: [0, 2, 4, 5, 7, 8, 10] },
    'ghedini': { name: 'Giorgio Federico Ghedini Scale', intervals: [0, 2, 3, 5, 7, 9, 10] },
    'vlad': { name: 'Roman Vlad Scale', intervals: [0, 1, 3, 4, 6, 8, 9] },
    'bussotti': { name: 'Sylvano Bussotti Scale', intervals: [0, 1, 2, 4, 6, 7, 9] },
    'evangelisti': { name: 'Franco Evangelisti Scale', intervals: [0, 1, 3, 5, 6, 8, 10] },
    'chailly': { name: 'Luciano Chailly Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'bucchi': { name: 'Valentino Bucchi Scale', intervals: [0, 2, 3, 5, 7, 8, 10] },
    'frontini': { name: 'Francesco Paolo Frontini Scale', intervals: [0, 2, 4, 5, 7, 9, 10] },
    'zandonai': { name: 'Riccardo Zandonai Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'wolf-ferrari': { name: 'Ermanno Wolf-Ferrari Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'boito': { name: 'Arrigo Boito Scale', intervals: [0, 2, 3, 5, 7, 8, 11] },
    'ponchielli': { name: 'Amilcare Ponchielli Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'catalani': { name: 'Alfredo Catalani Scale', intervals: [0, 2, 4, 5, 7, 8, 11] },
    'mascagni': { name: 'Pietro Mascagni Scale', intervals: [0, 2, 4, 5, 7, 9, 10] },
    'leoncavallo': { name: 'Ruggero Leoncavallo Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'giordano': { name: 'Umberto Giordano Scale', intervals: [0, 2, 3, 5, 7, 8, 10] },
    'cilea': { name: 'Francesco Cilea Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'alfano': { name: 'Franco Alfano Scale', intervals: [0, 2, 3, 5, 7, 8, 11] },
    'montemezzi': { name: 'Italo Montemezzi Scale', intervals: [0, 2, 4, 5, 7, 8, 11] },
    'pizzi': { name: 'Emilio de Pizzi Scale', intervals: [0, 2, 4, 5, 7, 9, 10] },
    'refice': { name: 'Licinio Refice Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'perosi': { name: 'Lorenzo Perosi Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'sinigaglia': { name: 'Leone Sinigaglia Scale', intervals: [0, 2, 3, 5, 7, 9, 10] },
    'sgambati': { name: 'Giovanni Sgambati Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'martucci': { name: 'Giuseppe Martucci Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'bossi': { name: 'Marco Enrico Bossi Scale', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'frescobaldi': { name: 'Girolamo Frescobaldi Mode', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'monteverdi': { name: 'Claudio Monteverdi Mode', intervals: [0, 2, 4, 5, 7, 9, 10] },
    'palestrina': { name: 'Giovanni Palestrina Mode', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'byrd': { name: 'William Byrd Mode', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'tallis': { name: 'Thomas Tallis Mode', intervals: [0, 2, 4, 5, 7, 9, 10] },
    'dowland': { name: 'John Dowland Mode', intervals: [0, 2, 3, 5, 7, 8, 10] },
    'purcell': { name: 'Henry Purcell Mode', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'lully': { name: 'Jean-Baptiste Lully Mode', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'rameau': { name: 'Jean-Philippe Rameau Mode', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'couperin': { name: 'François Couperin Mode', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'charpentier': { name: 'Marc-Antoine Charpentier Mode', intervals: [0, 2, 4, 5, 7, 9, 10] },
    'corelli': { name: 'Arcangelo Corelli Mode', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'vivaldi': { name: 'Antonio Vivaldi Mode', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'scarlatti': { name: 'Domenico Scarlatti Mode', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'telemann': { name: 'Georg Philipp Telemann Mode', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'handel': { name: 'George Frideric Handel Mode', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'bach': { name: 'Johann Sebastian Bach Mode', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'mozart': { name: 'Wolfgang Amadeus Mozart Mode', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'haydn': { name: 'Joseph Haydn Mode', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'beethoven': { name: 'Ludwig van Beethoven Mode', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'schubert': { name: 'Franz Schubert Mode', intervals: [0, 2, 3, 5, 7, 8, 11] },
    'mendelssohn': { name: 'Felix Mendelssohn Mode', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'schumann': { name: 'Robert Schumann Mode', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'chopin': { name: 'Frédéric Chopin Mode', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'liszt': { name: 'Franz Liszt Mode', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'wagner': { name: 'Richard Wagner Mode', intervals: [0, 1, 4, 6, 8, 10] },
    'brahms': { name: 'Johannes Brahms Mode', intervals: [0, 2, 4, 5, 7, 9, 11] },
    'dvorak': { name: 'Antonín Dvořák Mode', intervals: [0, 2, 3, 5, 7, 9, 10] },
    'smetana': { name: 'Bedřich Smetana Mode', intervals: [0, 2, 4, 5, 7, 9, 10] },
    'grieg': { name: 'Edvard Grieg Mode', intervals: [0, 2, 3, 5, 7, 8, 11] },
    'sibelius': { name: 'Jean Sibelius Mode', intervals: [0, 2, 3, 5, 7, 8, 10] },
    'nielsen': { name: 'Carl Nielsen Mode', intervals: [0, 2, 4, 5, 7, 9, 11] }
};